name: Publish Node Alpine Puppeteer

on: 
  - workflow_dispatch
  
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Checkout action repository
        uses: actions/checkout@v3
        with:
          repository: heronlabs/publish-docker-action
          ref: 3.1.0
          token: ${{ secrets.AUTHOR_PERSONAL_ACCESS}}
          path: ./publish-docker-action

      - name: Run action
        uses: './publish-docker-action/application/github'
        with:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_AUTH_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          FILE_NAME: Dockerfile
          NAME: "node-alpine-puppeteer"
          TAG: "latest"
          REPO: "heronlabs/node-alpine-puppeteer"
